### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by Kreshnik** [vuejs/laravel-elixir-vue-2#16]
After updating vuejs, gulp is not able to compile the vuejs templates. 
````
Vue packages version mismatch:

- vue@2.0.5
- vue-template-compiler@2.0.3

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.
```

**Comment by yyx990803** [comment]
As the message suggests, re-sintalling `laravel-elixir-vue-2` should resolve the issue.

**Comment by alex-thompson** [comment]
Running `npm install vue-template-compiler` brought the template compiler up to the latest version and solved it for me.

**Comment by kluplau** [comment]
I got this issue on Laravel Spark, and Googled me in here, so if anyone else does this you might also need to update `vue`, if you update `vue-template-compiler`.

**Comment by adrian12121989** [comment]
just run npm update 
it worked for me it will update all of the packages to the latest version

**Comment by hersonpc** [comment]
I had same error and a npm update soved it for me.

Just run:
`npm update`
