### ISSUE TITLE
Module build failed with spread transformation

### ISSUE THREAD

**Issue by RomanLavrinenko** [vuejs/laravel-elixir-vue-2#19]
HI, I try to use Vuex and it's syntax like in examples:
```
...
  computed: mapGetters({
    foo: 'foo',
    bar: 'bar',
    buz: 'buz'
  }),
  methods: {
    ...mapActions([
      'foo',
      'bar'
    ]),
    buz() {
      
    }
  },
...
```

but got error when build app with gulp:
```
{ [Error: ./~/buble-loader!./resources/assets/js/components/search/component.js
Module build failed: Error
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:6206:11)
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:880:10)
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:6352:31)
    at /var/.../node_modules/buble/dist/buble.umd.js:878:59
    at Array.forEach (native)
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:878:10)
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:6192:31)
    at Node.transpile (/var/.../node_modules/buble/dist/buble.umd.js:880:10)
    at /var/.../node_modules/buble/dist/buble.umd.js:878:59
```

my gulpfile looks like:
```
var elixir = require('laravel-elixir');
require('laravel-elixir-vue-2');
elixir(function(mix) {
  mix.webpack('foo.js', '/bar.js')
})
```
If i'm not using syntax like `...mapActions` all good
Could you please tell me is it possible to use spread syntax just using laravel-elixir-vue-2 or i should find an additional plugin to make this work?

**Comment by mirkojotic** [comment]
+1 same issue

**Comment by wskc** [comment]
Be sure to use **laravel-elixir-vue-2@0.3.0** as the [buble-loader option for Object.assign](https://github.com/vuejs/laravel-elixir-vue-2/commit/336e76e3e93d5f023a4219b8ecc2fdeb435d983f#diff-168726dbe96b3ce427e7fedce31bb0bc) was added.
This happens because Laravel is using the previous minor version [in its npm dependencies](https://github.com/laravel/laravel/blob/v5.3.30/package.json) (as of its latest 5.3.* release)

**Comment by RomanLavrinenko** [comment]
@wskc Thanks! That is works for me.
NOTE: Also in my package.json i had dev dependencies for 'vue-loader', 'vue', 'vue-template-compiler', ... which are also had lower versions. I've fixed them with versions which i found  via link provided by @wskc (https://github.com/vuejs/laravel-elixir-vue-2/commit/336e76e3e93d5f023a4219b8ecc2fdeb435d983f#diff-168726dbe96b3ce427e7fedce31bb0bc)
Hope this could be helpful for others
