### ISSUE TITLE
Support Vue 2.3

### ISSUE THREAD

**Issue by jbrooksuk** [vuejs/laravel-elixir-vue-2#29]
Currently, this package does not work with Vue 2.3

**Comment by dymen1** [comment]
Any idea on how to fix this? 
Is it just me or does this repo look pretty dead? If so, I might fork it.

**Comment by jbrooksuk** [comment]
@dymen1 no idea, sorry. I think it needs forking.

**Comment by jbrooksuk** [comment]
@dymen1 I forked to https://github.com/BlueBayTravel/laravel-elixir-vue-2
